name: static-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check formatting
        run: nix develop -c cargo fmt --check
      - name: Run linting
        run: nix develop -c cargo clippy
      - name: Run tests
        run: nix develop -c cargo test --locked --frozen --all-features
